version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: delivery
    ports:
      - "5432:5432"
