services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: delivery
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
